Repository CliMA/ClimateMachine.jl, pull requests merged in 2020-06, with the labels that each got.

#1180 Fix docs and typos in StateCheck.jl
  src/Diagnostics/Debug/StateCheck.jl
Labels: Documentation

#1006 Automate tutorial files from pages array
  docs/list_of_tutorials.jl
  docs/pages_helper.jl
Labels: Documentation

#1185 Fix broken `Writers` test
  src/InputOutput/Writers/jld2_writer.jl
  test/InputOutput/Writers/runtests.jl
  test/InputOutput/runtests.jl
Labels: CI / CD

#1186 Fix reference state definition, add tests
  src/Atmos/TemperatureProfiles/TemperatureProfiles.jl
  test/Atmos/TemperatureProfiles/runtests.jl
  test/Atmos/runtests.jl
  test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
Labels: Bug-fix

#1172 Separate cli arg parsing from initialization
  experiments/AtmosGCM/heldsuarez.jl
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/surfacebubble.jl
  experiments/AtmosLES/taylor-green.jl
  experiments/OceanBoxGCM/homogeneous_box.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  src/Driver/Driver.jl
Labels: User Interface

#1125 Driver update: Solver types for explicit, IMEX, multirate, and MIS methods
  experiments/AtmosGCM/heldsuarez.jl
  experiments/OceanBoxGCM/homogeneous_box.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  src/Driver/SolverTypes/ExplicitSolverType.jl
  src/Driver/SolverTypes/IMEXSolverType.jl
  src/Driver/SolverTypes/MISSolverType.jl
  src/Driver/SolverTypes/MultirateSolverType.jl
  src/Driver/SolverTypes/SolverTypes.jl
  src/Driver/driver_configs.jl
  src/Driver/solver_configs.jl
  test/Diagnostics/diagnostic_fields_test.jl
  test/Driver/cr_unit_tests.jl
  test/Driver/gcm_driver_test.jl
  test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
  test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
  tutorials/Atmos/dry_rayleigh_benard.jl
  tutorials/Atmos/heldsuarez.jl
  tutorials/Atmos/risingbubble.jl
Labels: Timestepping, User Interface, enhancement

#1184 Add reference val check to test_ocean_gyre.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  experiments/OceanBoxGCM/ocean_gyre_refvals.jl
  src/Diagnostics/Debug/StateCheck.jl
  test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
  test/Ocean/HydrostaticBoussinesq/test_ocean_gyre_refvals.jl
Labels: CI / CD, Continuous Integration, Defensive programming, Ocean

#1188 Add disable_custom_logger option to Driver
  docs/make.jl
  src/Driver/Driver.jl
  src/Numerics/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl
Labels: Documentation

#1218 Fix and add docs
  README.md
  docs/list_of_apis.jl
  docs/src/APIs/Atmos/AtmosModel.md
  docs/src/APIs/Diagnostics/Diagnostics.md
  docs/src/APIs/Driver/index.md
  docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
  docs/src/APIs/Numerics/SystemSolvers/SystemSolvers.md
  docs/src/GettingStarted/Installation.md
  docs/src/HowToGuides/Numerics/DGMethods/how_to_make_a_balance_law.md
  docs/src/HowToGuides/Numerics/ODESolvers/Timestepping.md
  docs/src/HowToGuides/Numerics/SystemSolvers/IterativeSolvers.md
  docs/src/Theory/Common/SurfaceFluxes.md
  src/Atmos/Model/AtmosModel.jl
  src/Common/SurfaceFluxes/SurfaceFluxes.jl
  src/Common/Thermodynamics/relations.jl
  src/Numerics/ODESolvers/GenericCallbacks.jl
  src/Numerics/ODESolvers/ODESolvers.jl
  src/Numerics/SystemSolvers/batched_generalized_minimal_residual_solver.jl
Labels: Documentation

#1182 Add filter targets and filter perturbations in Held-Suarez
  experiments/AtmosGCM/heldsuarez.jl
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/surfacebubble.jl
  experiments/AtmosLES/taylor-green.jl
  src/Arrays/MPIStateArrays.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/filters.jl
  src/Numerics/Mesh/Filters.jl
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
  test/Numerics/Mesh/filter.jl
  tutorials/Atmos/dry_rayleigh_benard.jl
  tutorials/Atmos/heldsuarez.jl
  tutorials/Atmos/risingbubble.jl
  tutorials/Microphysics/ex_2_Kessler.jl
  tutorials/Numerics/DGMethods/nonnegative.jl
Labels: AtmosDycore, Bug-fix

#1219 Fix held suarez tutorial, and run in docs
  docs/list_of_tutorials.jl
  tutorials/Atmos/heldsuarez.jl
Labels: Documentation

#1236 Fix docs and remove slurm-tested broken tutorials from docs
  docs/list_of_tutorials.jl
  docs/src/Contributing.md
  tutorials/Atmos/dry_rayleigh_benard.jl
  tutorials/Atmos/risingbubble.jl
  tutorials/Diagnostics/Debug/StateCheck.jl
  tutorials/Land/Heat/heat_equation.jl
  tutorials/Numerics/DGMethods/nonnegative.jl
  tutorials/Numerics/SystemSolvers/bgmres.jl
  tutorials/Numerics/SystemSolvers/cg.jl
  tutorials/topo.jl
Labels: Documentation

#1195 Diagnostics groups append to NetCDF
  experiments/OceanBoxGCM/homogeneous_box.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  src/Diagnostics/Diagnostics.jl
  src/Diagnostics/atmos_gcm_default.jl
  src/Diagnostics/atmos_les_core.jl
  src/Diagnostics/atmos_les_default.jl
  src/Diagnostics/dump_aux.jl
  src/Diagnostics/dump_state.jl
  src/Diagnostics/dump_state_and_aux.jl
  src/Diagnostics/groups.jl
  src/Driver/Driver.jl
  src/Driver/driver_configs.jl
  src/Driver/solver_configs.jl
  src/InputOutput/Writers/Writers.jl
  src/InputOutput/Writers/jld2_writer.jl
  src/InputOutput/Writers/netcdf_writer.jl
  test/Diagnostics/sin_test.jl
  test/InputOutput/Writers/runtests.jl
  test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
  test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
  tutorials/Atmos/heldsuarez.jl
Labels: Diagnostics

#1234 Switch CI to use Github Actions, run tests in parallel and fast fail when possible
  .github/workflows/Coverage.yaml
  .github/workflows/Documenter.yaml
  .github/workflows/JuliaFormatter.yml
  .github/workflows/Linux-UnitTests.yml
  .github/workflows/OS-UnitTests.yml
  README.md
  azure-pipelines.yml
  bors.toml
  docs/src/Contributing.md
  slurmci-test.toml
  test/Atmos/runtests.jl
  test/Common/runtests.jl
  test/InputOutput/runtests.jl
  test/Numerics/DGMethods/runtests.jl
  test/Numerics/runtests.jl
  test/Utilities/runtests.jl
  test/runtests.jl
Labels: CI

#1232 Add simple hydrostatic spin-down test for Ocean Model
  experiments/OceanBoxGCM/hydrostatic_spindown.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  experiments/OceanBoxGCM/refvals/hydrostatic_spindown_refvals.jl
  experiments/OceanBoxGCM/refvals/ocean_gyre_refvals.jl
  slurmci-test.toml
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
  test/Ocean/runtests.jl
Labels: Ocean, tests

#1244 Make docs strict
  README.md
  docs/list_of_apis.jl
  docs/make.jl
  docs/src/APIs/Arrays/Arrays.md
  docs/src/APIs/Atmos/AtmosModel.md
  docs/src/APIs/Atmos/Microphysics.md
  docs/src/APIs/Atmos/TemperatureProfiles.md
  docs/src/APIs/Common/Thermodynamics.md
  docs/src/APIs/Diagnostics/Diagnostics.md
  docs/src/APIs/Diagnostics/InputOutput.md
  docs/src/APIs/Diagnostics/StateCheck.md
  docs/src/APIs/Driver/index.md
  docs/src/APIs/Numerics/DGMethods/NumericalFluxes.md
  docs/src/APIs/Numerics/Meshes/Mesh.md
  docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
  docs/src/APIs/Numerics/SystemSolvers/SystemSolvers.md
  docs/src/APIs/Ocean/HydrostaticBoussinesq.md
  docs/src/APIs/Utilities/ArtifactWrappers.md
  docs/src/APIs/Utilities/Checkpoint.md
  docs/src/APIs/Utilities/SingleStackUtils.md
  docs/src/APIs/Utilities/TicToc.md
  docs/src/APIs/Utilities/VariableTemplates.md
  docs/src/DevDocs/AcceptableUnicode.md
  docs/src/DevDocs/CodeStyle.md
  docs/src/DevDocs/VariableList.md
  docs/src/GettingStarted/Atmos.md
  docs/src/Theory/Atmos/Microphysics.md
  docs/src/Theory/Atmos/Model/turbulence.md
  src/Driver/Driver.jl
  src/Numerics/DGMethods/Courant.jl
  src/Numerics/Mesh/Topologies.jl
  src/Numerics/ODESolvers/BackwardEulerSolvers.jl
  src/Numerics/ODESolvers/MultirateInfinitesimalGARKDecoupledImplicit.jl
  src/Numerics/ODESolvers/MultirateInfinitesimalGARKExplicit.jl
  src/Utilities/SingleStackUtils/SingleStackUtils.jl
  tutorials/Atmos/burgers_single_stack.jl
  tutorials/Atmos/risingbubble.jl
  tutorials/Land/Heat/heat_equation.jl
Labels: Documentation

#1246 Fix formatting in burgers single stack tutorial
  tutorials/Atmos/burgers_single_stack.jl
Labels: Documentation

#1251 add separate precompile step for unit build matrix
  .github/workflows/Linux-UnitTests.yml
  .github/workflows/OS-UnitTests.yml
Labels: Bug-fix, CI

#1250 generate tutorial output in parallel
  .github/workflows/Documenter.yaml
  docs/clean_build_folder.jl
  docs/list_of_tutorials.jl
  docs/make.jl
Labels: CI, Documentation

#1256 Add 2D hydrostatic spindown test for SWModel
  slurmci-test.toml
  src/Ocean/ShallowWater/ShallowWaterModel.jl
  test/Ocean/HydrostaticBoussinesq/3D_hydrostatic_spindown.jl
  test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
  test/Ocean/ShallowWater/2D_hydrostatic_spindown.jl
  test/Ocean/ShallowWater/GyreDriver.jl
  test/Ocean/ShallowWater/GyreInABox.jl
  test/Ocean/refvals/2D_hydrostatic_spindown_refvals.jl
  test/Ocean/refvals/3D_hydrostatic_spindown_refvals.jl
  test/Ocean/refvals/test_ocean_gyre_refvals.jl
  test/Ocean/runtests.jl
Labels: Ocean, tests

#1067 ice microphysics
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/src/APIs/Atmos/Microphysics.md
  docs/src/APIs/Common/Thermodynamics.md
  docs/src/Theory/Atmos/Microphysics.md
  slurmci-test.toml
  src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
  src/Common/Thermodynamics/relations.jl
  test/Atmos/Parameterizations/Microphysics/KM_ice.jl
  test/Atmos/Parameterizations/Microphysics/KM_saturation_adjustment.jl
  test/Atmos/Parameterizations/Microphysics/KM_warm_rain.jl
  test/Atmos/Parameterizations/Microphysics/KinematicModel.jl
  test/Atmos/Parameterizations/Microphysics/runtests.jl
  test/Common/Thermodynamics/runtests.jl
  tutorials/Microphysics/ex_2_Kessler.jl
Labels: Documentation, Draft, Microphysics

#1050 Revamp thermodynamics reference state
  docs/src/APIs/Common/Thermodynamics.md
  src/Common/Thermodynamics/Thermodynamics.jl
  src/Common/Thermodynamics/relations.jl
  src/Common/Thermodynamics/states.jl
  test/Common/Thermodynamics/profiles.jl
  test/Common/Thermodynamics/runtests.jl
  test/Utilities/VariableTemplates/varsindex.jl
Labels: Documentation, Thermodynamics

#1248 Move orientations to Common/
  docs/list_of_apis.jl
  docs/src/APIs/Atmos/AtmosModel.md
  docs/src/APIs/Common/Orientations.md
  experiments/AtmosGCM/heldsuarez.jl
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/surfacebubble.jl
  experiments/AtmosLES/taylor-green.jl
  src/Atmos/Model/AtmosModel.jl
  src/ClimateMachine.jl
  src/Common/Orientations/Orientations.jl
  test/Atmos/Parameterizations/Microphysics/KinematicModel.jl
  test/Diagnostics/diagnostic_fields_test.jl
  test/Diagnostics/sin_test.jl
  test/Driver/cr_unit_tests.jl
  test/Driver/gcm_driver_test.jl
  test/Driver/mms3.jl
  test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
  test/Numerics/DGMethods/Euler/isentropicvortex.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_imex.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_mrigark.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_mrigark_implicit.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_multirate.jl
  test/Numerics/DGMethods/advection_diffusion/advection_sphere.jl
  test/Numerics/DGMethods/compressible_Navier_Stokes/density_current_model.jl
  test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl
  test/Numerics/DGMethods/courant.jl
  test/Numerics/Mesh/interpolation.jl
  tutorials/Atmos/agnesi_hs_lin.jl
  tutorials/Atmos/agnesi_nh_lin.jl
  tutorials/Atmos/dry_rayleigh_benard.jl
  tutorials/Atmos/heldsuarez.jl
  tutorials/Atmos/risingbubble.jl
Labels: Refactor

#1267 Convert SWModel to 2-component velocity
  src/Ocean/ShallowWater/ShallowWaterModel.jl
  test/Ocean/ShallowWater/2D_hydrostatic_spindown.jl
  test/Ocean/ShallowWater/GyreDriver.jl
  test/Ocean/ShallowWater/GyreInABox.jl
  test/Ocean/refvals/2D_hydrostatic_spindown_refvals.jl
Labels: Ocean, Refactor

#1266 Move balance law to its own module
  docs/list_of_apis.jl
  docs/src/APIs/BalanceLaws/BalanceLaws.md
  docs/src/APIs/Numerics/DGMethods/DGMethods.md
  docs/src/DevDocs/CodeStyle.md
  docs/src/HowToGuides/Numerics/DGMethods/how_to_make_a_balance_law.md
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/taylor-green.jl
  experiments/OceanBoxGCM/homogeneous_box.jl
  src/Atmos/Model/AtmosModel.jl
  src/BalanceLaws/BalanceLaws.jl
  src/BalanceLaws/interface.jl
  src/ClimateMachine.jl
  src/Common/Orientations/Orientations.jl
  src/Diagnostics/Diagnostics.jl
  src/Driver/Driver.jl
  src/Numerics/DGMethods/DGMethods.jl
  src/Numerics/DGMethods/DGModel.jl
  src/Numerics/DGMethods/NumericalFluxes.jl
  src/Numerics/DGMethods/create_states.jl
  src/Numerics/SystemSolvers/SystemSolvers.jl
  src/Ocean/HydrostaticBoussinesq/BoundaryConditions.jl
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  src/Ocean/ShallowWater/ShallowWaterModel.jl
  src/Utilities/Callbacks/Callbacks.jl
  src/Utilities/SingleStackUtils/SingleStackUtils.jl
  test/Atmos/Parameterizations/Microphysics/KinematicModel.jl
  test/Diagnostics/diagnostic_fields_test.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_imex.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_mrigark.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_mrigark_implicit.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_multirate.jl
  test/Numerics/DGMethods/advection_diffusion/advection_diffusion_model.jl
  test/Numerics/DGMethods/advection_diffusion/advection_sphere.jl
  test/Numerics/DGMethods/advection_diffusion/hyperdiffusion_model.jl
  test/Numerics/DGMethods/compressible_Navier_Stokes/mms_model.jl
  test/Numerics/DGMethods/conservation/sphere.jl
  test/Numerics/DGMethods/courant.jl
  test/Numerics/DGMethods/integral_test.jl
  test/Numerics/DGMethods/integral_test_sphere.jl
  test/Numerics/DGMethods/vars_test.jl
  test/Numerics/Mesh/filter.jl
  test/Numerics/SystemSolvers/bandedsystem.jl
  test/Numerics/SystemSolvers/poisson.jl
  test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
  test/Ocean/ShallowWater/2D_hydrostatic_spindown.jl
  tutorials/Atmos/burgers_single_stack.jl
  tutorials/Land/Heat/heat_equation.jl
Labels: Refactor

#1273 Revert Thermo changes to fix CI
  src/Common/Thermodynamics/relations.jl
  test/Common/Thermodynamics/profiles.jl
  test/Common/Thermodynamics/runtests.jl
Labels: Thermodynamics

#1257 Add SplitExplicitStepper with decoupled spin-down test
  docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
  slurmci-test.toml
  src/BalanceLaws/interface.jl
  src/ClimateMachine.jl
  src/Numerics/DGMethods/DGModel.jl
  src/Numerics/ODESolvers/ODESolvers.jl
  src/Numerics/ODESolvers/SplitExplicitMethod.jl
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  src/Ocean/SplitExplicit/SplitExplicitModel.jl
  test/Ocean/SplitExplicit/hydrostatic_spindown.jl
  test/Ocean/refvals/hydrostatic_spindown_refvals.jl
  test/Ocean/runtests.jl
Labels: Ocean, Timestepping, tests

#1271 Fix PR template links
  .github/pull_request_template.md
Labels: Documentation

#1242 Diagnostics group for perturbations from reference state
  docs/src/APIs/Atmos/AtmosModel.md
  docs/src/APIs/Diagnostics/Diagnostics.md
  experiments/AtmosGCM/heldsuarez.jl
  src/Atmos/Model/ref_state.jl
  src/Diagnostics/Diagnostics.jl
  src/Diagnostics/atmos_gcm_default.jl
  src/Diagnostics/atmos_les_core.jl
  src/Diagnostics/atmos_les_default.jl
  src/Diagnostics/atmos_refstate_perturbations.jl
  src/Diagnostics/dump_aux.jl
  src/Diagnostics/dump_state.jl
  src/Diagnostics/groups.jl
  src/Diagnostics/variables.jl
Labels: Diagnostics

#1260 Update to CUDA 1.0
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  src/Arrays/CMBuffers.jl
  src/Arrays/MPIStateArrays.jl
  src/Diagnostics/Diagnostics.jl
  src/Diagnostics/atmos_gcm_default.jl
  src/Diagnostics/atmos_refstate_perturbations.jl
  src/Driver/Driver.jl
  src/Numerics/DGMethods/DGModel.jl
  src/Numerics/Mesh/Filters.jl
  src/Numerics/Mesh/Grids.jl
  src/Numerics/Mesh/Interpolation.jl
  src/Numerics/SystemSolvers/SystemSolvers.jl
  src/Numerics/SystemSolvers/batched_generalized_minimal_residual_solver.jl
  src/Utilities/Callbacks/Callbacks.jl
  test/Numerics/Mesh/interpolation.jl
  test/Numerics/SystemSolvers/bgmres.jl
  test/Numerics/SystemSolvers/cg.jl
  test/runtests_gpu.jl
Labels: GPU

#1275 Add exceptions to thermo for failed convergence
  src/Common/Thermodynamics/relations.jl
  test/Common/Thermodynamics/runtests.jl
Labels: Thermodynamics

#1249 Create module TurbulenceClosures: move from `Atmos`->`Common`
  docs/list_of_apis.jl
  docs/list_of_theory_docs.jl
  docs/src/APIs/Atmos/AtmosModel.md
  docs/src/APIs/Common/TurbulenceClosures.md
  docs/src/Theory/Common/Turbulence.md
  experiments/AtmosGCM/heldsuarez.jl
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/surfacebubble.jl
  experiments/AtmosLES/taylor-green.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/bc_energy.jl
  src/Atmos/Model/courant.jl
  src/ClimateMachine.jl
  src/Common/Orientations/Orientations.jl
  src/Common/TurbulenceClosures/TurbulenceClosures.jl
  src/Diagnostics/atmos_gcm_default.jl
  src/Diagnostics/atmos_les_default.jl
  test/Diagnostics/diagnostic_fields_test.jl
  test/Driver/cr_unit_tests.jl
  test/Driver/driver_test.jl
  test/Driver/gcm_driver_test.jl
  test/Driver/mms3.jl
  test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
  test/Numerics/DGMethods/Euler/isentropicvortex.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_imex.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_mrigark.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_mrigark_implicit.jl
  test/Numerics/DGMethods/Euler/isentropicvortex_multirate.jl
  test/Numerics/DGMethods/compressible_Navier_Stokes/density_current_model.jl
  test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl
  test/Numerics/DGMethods/compressible_Navier_Stokes/ref_state.jl
  test/Numerics/DGMethods/courant.jl
  test/Numerics/DGMethods/horizontal_integral_test.jl
  test/Numerics/Mesh/interpolation.jl
  tutorials/Atmos/agnesi_hs_lin.jl
  tutorials/Atmos/agnesi_nh_lin.jl
  tutorials/Atmos/densitycurrent.jl
  tutorials/Atmos/dry_rayleigh_benard.jl
  tutorials/Atmos/heldsuarez.jl
  tutorials/Atmos/risingbubble.jl
Labels: Refactor

#1293 Add scaled-increment interface to main DG evaluation
  docs/src/APIs/Numerics/DGMethods/DGMethods.md
  src/Numerics/DGMethods/DGModel.jl
  src/Numerics/DGMethods/DGModel_kernels.jl
Labels: AtmosDycore

#1302 Add supermodule `Ocean` around SWModel and HBModel
  docs/src/APIs/BalanceLaws/BalanceLaws.md
  experiments/OceanBoxGCM/homogeneous_box.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  src/BalanceLaws/BalanceLaws.jl
  src/ClimateMachine.jl
  src/Driver/Driver.jl
  src/Ocean/HydrostaticBoussinesq/BoundaryConditions.jl
  src/Ocean/HydrostaticBoussinesq/Courant.jl
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  src/Ocean/Ocean.jl
  src/Ocean/ShallowWater/ShallowWaterModel.jl
  src/Ocean/SplitExplicit/SplitExplicitModel.jl
  test/Ocean/HydrostaticBoussinesq/3D_hydrostatic_spindown.jl
  test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
  test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
  test/Ocean/ShallowWater/2D_hydrostatic_spindown.jl
  test/Ocean/ShallowWater/GyreInABox.jl
  test/Ocean/SplitExplicit/hydrostatic_spindown.jl
Labels: Ocean, Refactor

#1295 cache artifacts in GitHub Actions
  .github/workflows/Documenter.yaml
  .github/workflows/Linux-UnitTests.yml
  .github/workflows/OS-UnitTests.yml
Labels: CI

#1303 Add documentation for I/O behavior
  docs/list_of_apis.jl
  docs/src/APIs/Diagnostics/Diagnostics.md
  docs/src/APIs/Driver/index.md
  docs/src/APIs/InputOutput/index.md
  docs/src/APIs/Numerics/DGMethods/Courant.md
  docs/src/APIs/Utilities/ArtifactWrappers.md
  docs/src/GettingStarted/RunningClimateMachine.md
  experiments/AtmosGCM/heldsuarez.jl
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/surfacebubble.jl
  experiments/AtmosLES/taylor-green.jl
  experiments/OceanBoxGCM/homogeneous_box.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  src/ClimateMachine.jl
  src/Driver/Callbacks/Callbacks.jl
  src/Driver/Driver.jl
  src/Driver/diagnostics_configs.jl
  src/InputOutput/ArtifactWrappers/ArtifactWrappers.jl
  test/Ocean/HydrostaticBoussinesq/3D_hydrostatic_spindown.jl
  tutorials/Atmos/agnesi_hs_lin.jl
  tutorials/Atmos/agnesi_nh_lin.jl
  tutorials/Atmos/densitycurrent.jl
Labels: Documentation, User Interface
