Repository CliMA/ClimateMachine.jl, pull requests merged in 2020-11, with the labels that each got.

#1656 Decompose discretization kernels into horizontal and vertical calls
  src/Numerics/DGMethods/DGModel.jl
  src/Numerics/DGMethods/DGModel_kernels.jl
  src/Numerics/Mesh/Topologies.jl
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  src/Ocean/SplitExplicit/Communication.jl
  src/Ocean/SplitExplicit/HydrostaticBoussinesqCoupling.jl
  src/Ocean/SplitExplicit01/Communication.jl
  src/Ocean/SplitExplicit01/OceanModel.jl
Labels: Defensive programming, House cleaning, Numerics, interface change

#1689 Add custom filter
  .buildkite/pipeline.yml
  docs/src/APIs/Numerics/DGMethods/DGMethods.md
  src/Numerics/DGMethods/DGMethods.jl
  src/Numerics/DGMethods/custom_filter.jl
  test/Numerics/DGMethods/custom_filter.jl
  test/Numerics/DGMethods/runtests.jl
Labels: AtmosTCC, EDMF

#1710 Add internal energies of dry air, vapor, liquid and ice
  docs/src/APIs/Common/Thermodynamics.md
  src/Common/Thermodynamics/relations.jl
  test/Common/Thermodynamics/runtests.jl
Labels: Atmos, Microphysics

#1724 Move Gravity to new tendency specification
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/source.jl
  src/Atmos/Model/tendencies_momentum.jl
Labels: Atmos

#1716 Experimental CartesianField abstractions for plotting and simple analysis, plus two new Ocean tutorials
  .gitignore
  docs/list_of_tutorials.jl
  src/Ocean/CartesianDomains/CartesianDomains.jl
  src/Ocean/CartesianDomains/cartesian_domain.jl
  src/Ocean/CartesianDomains/cartesian_field.jl
  src/Ocean/CartesianDomains/rectangular_element.jl
  src/Ocean/Fields.jl
  src/Ocean/Ocean.jl
  src/Ocean/OceanProblems/OceanProblems.jl
  src/Ocean/OceanProblems/SimpleBoxProblem.jl
  src/Ocean/OceanProblems/homogeneous_box.jl
  src/Ocean/OceanProblems/initial_value_problem.jl
  src/Ocean/OceanProblems/ocean_gyre.jl
  src/Ocean/OceanProblems/shallow_water_initial_states.jl
  src/Ocean/OceanProblems/simple_box_problem.jl
  test/Ocean/OceanProblems/test_initial_value_problem.jl
  test/Ocean/runtests.jl
  tutorials/Ocean/geostrophic_adjustment.jl
  tutorials/Ocean/radiating_eddy.jl
Labels: Ocean 🌊

#1735 Update installation guide: use CLIMATEMACHINE_SETTINGS_DISABLE_GPU
  docs/src/GettingStarted/Installation.md
Labels: Documentation 📜, House cleaning 🧹, enhancement

#1737 Move Coriolis and GeoForcing to new tendency specification
  docs/src/GettingStarted/Atmos.md
  experiments/AtmosLES/dycoms.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/source.jl
  src/Atmos/Model/tendencies_momentum.jl
Labels: Refactor

#1751 Driver update: Variable polynomial order
  src/Driver/driver_configs.jl
  test/Driver/driver_test.jl
  test/Driver/gcm_driver_test.jl
  test/Driver/mms3.jl
Labels: DG Kernels, Numerics 🔢, enhancement, interface change

#1750 Move RayleighSponge to new tendency specification
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/schar_scalar_advection.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/source.jl
  src/Atmos/Model/tendencies_momentum.jl
  src/BalanceLaws/sum_tendencies.jl
  tutorials/Atmos/agnesi_hs_lin.jl
  tutorials/Atmos/agnesi_nh_lin.jl
  tutorials/Atmos/heldsuarez.jl
Labels: Refactor

#1701 Working Squall line with NonEquilMoist
  .buildkite/pipeline.yml
  experiments/AtmosLES/Artifacts.toml
  experiments/AtmosLES/squall_line.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/declare_prognostic_vars.jl
Labels: Atmos

#1756 Add some documentation
  docs/list_of_dev_docs.jl
  docs/list_of_how_to_guides.jl
  docs/src/DevDocs/DiagnosticVariableList.md
  docs/src/DevDocs/ModelOutput.md
  docs/src/DevDocs/ModelVariableList.md
  docs/src/GettingStarted/RunningClimateMachine.md
  docs/src/HowToGuides/Diagnostics/UsingDiagnostics.md
  src/Diagnostics/atmos_gcm_default.jl
  src/Diagnostics/atmos_gcm_spectra.jl
  src/Diagnostics/atmos_les_core.jl
  src/Diagnostics/atmos_les_default.jl
  src/Diagnostics/atmos_les_default_perturbations.jl
  src/Diagnostics/atmos_les_spectra.jl
  src/Diagnostics/atmos_refstate_perturbations.jl
  src/Diagnostics/atmos_turbulence_stats.jl
  src/Diagnostics/dump_aux.jl
  src/Diagnostics/dump_state.jl
  src/Driver/Driver.jl
Labels: ClimateMachine 🤖, Diagnostics, Documentation 📜

#1768 Clean up thermo tests
  test/Common/Thermodynamics/runtests.jl
Labels: Thermodynamics

#1773 Fix thermo print statements
  src/Common/Thermodynamics/relations.jl
Labels: Thermodynamics

#1687 Extract remaining citations
  docs/bibliography.bib
  docs/src/Theory/Atmos/Microphysics.md
  docs/src/Theory/Common/SurfaceFluxes.md
  experiments/AtmosGCM/GCMDriver/baroclinicwave_problem.jl
  experiments/AtmosLES/bomex_model.jl
  experiments/AtmosLES/convective_bl_model.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/schar_scalar_advection.jl
  experiments/AtmosLES/stable_bl_model.jl
  experiments/AtmosLES/taylor_green.jl
  src/Atmos/Model/AtmosModel.jl
  src/Common/Spectra/power_spectrum_gcm.jl
  src/Common/Spectra/spherical_helper.jl
  src/Common/SurfaceFluxes/SurfaceFluxes.jl
  src/Common/SurfaceFluxes/UniversalFunctions.jl
  src/Common/TurbulenceClosures/TurbulenceClosures.jl
  src/Driver/SolverTypes/IMEXSolverType.jl
  src/Driver/SolverTypes/MISSolverType.jl
  src/Driver/SolverTypes/MultirateSolverType.jl
  src/Numerics/DGMethods/NumericalFluxes.jl
  src/Numerics/Mesh/BrickMesh.jl
  src/Numerics/Mesh/Elements.jl
  src/Numerics/Mesh/Filters.jl
  src/Numerics/Mesh/Metrics.jl
  src/Numerics/Mesh/Topologies.jl
  src/Numerics/ODESolvers/AdditiveRungeKuttaMethod.jl
  src/Numerics/ODESolvers/LowStorageRungeKuttaMethod.jl
  src/Numerics/ODESolvers/MultirateInfinitesimalGARKDecoupledImplicit.jl
  src/Numerics/ODESolvers/MultirateInfinitesimalGARKExplicit.jl
  src/Numerics/ODESolvers/MultirateInfinitesimalStepMethod.jl
  src/Numerics/ODESolvers/MultirateRungeKuttaMethod.jl
  src/Numerics/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl
  src/Numerics/SystemSolvers/columnwise_lu_solver.jl
  src/Numerics/SystemSolvers/generalized_conjugate_residual_solver.jl
  src/Numerics/SystemSolvers/generalized_minimal_residual_solver.jl
  test/Atmos/Parameterizations/Microphysics/KM_ice.jl
  test/Atmos/Parameterizations/Microphysics/KinematicModel.jl
  test/Atmos/Parameterizations/Microphysics/runtests.jl
  test/Numerics/DGMethods/advection_diffusion/advection_sphere.jl
  test/Numerics/DGMethods/compressible_Navier_Stokes/density_current_model.jl
  test/Numerics/Mesh/filter_TMAR.jl
  test/Numerics/ODESolvers/ode_tests_convergence.jl
  tutorials/Atmos/densitycurrent.jl
  tutorials/Atmos/heldsuarez.jl
Labels: Documentation 📜

#1725 Move first order moisture flux to new tendency specification
  .buildkite/pipeline.yml
  experiments/AtmosLES/bomex_single_stack.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/moisture.jl
  src/Atmos/Model/tendencies_moisture.jl
Labels: Atmos

#1774 Move liq and ice sources to new tend spec.
  experiments/AtmosLES/bomex_model.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/squall_line.jl
  experiments/AtmosLES/stable_bl_model.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/moisture.jl
  src/Atmos/Model/source.jl
  src/Atmos/Model/tendencies_moisture.jl
Labels: Atmos, Refactor

#1781 Add DOIs to .bib, remove urls
  docs/bibliography.bib
Labels: Documentation 📜

#1784 Add `sample_rate` to plothelper funcs
  docs/plothelpers.jl
Labels: plotting

#1791 VTK support for multiple polynomial orders
  src/InputOutput/VTK/writemesh.jl
  src/InputOutput/VTK/writevtk.jl
  test/InputOutput/VTK/runtests.jl
  test/Numerics/SystemSolvers/bandedsystem.jl
Labels: Diagnostics, IO 💾, enhancement

#1786 Prep for new tendency spec
  docs/src/APIs/Atmos/AtmosModel.md
  docs/src/HowToGuides/Atmos/PrecipitationModelChoices.md
  experiments/AtmosLES/dycoms.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/moisture.jl
  src/Atmos/Model/precipitation.jl
  src/Atmos/Model/radiation.jl
  src/Atmos/Model/source.jl
  src/Atmos/Model/tendencies_momentum.jl
  src/Atmos/Model/tracers.jl
  src/Common/TurbulenceConvection/TurbulenceConvection.jl
  src/Diagnostics/atmos_les_default.jl
  test/Atmos/EDMF/edmf_kernels.jl
Labels: Refactor

#1752 Support for metrics with polynomial order `N = 0` elements
  .buildkite/pipeline.yml
  src/InputOutput/VTK/writevtk.jl
  src/Numerics/Mesh/Elements.jl
  src/Numerics/Mesh/Grids.jl
  src/Numerics/Mesh/Metrics.jl
  test/InputOutput/VTK/runtests.jl
  test/Numerics/DGMethods/advection_diffusion/fvm_advection.jl
  test/Numerics/Mesh/BrickMesh.jl
  test/Numerics/Mesh/Elements.jl
  test/Numerics/Mesh/Metrics.jl
Labels: DG Kernels, enhancement, geometry
