Repository CliMA/ClimateMachine.jl, pull requests merged in 2020-04, with the labels that each got.

#731 Make MPIStateArray Vars aware
  slurmci-test.toml
  src/Arrays/MPIStateArrays.jl
  src/DGmethods/balancelaw.jl
  test/Arrays/runtests.jl
  test/Arrays/varsindex.jl
  test/DGmethods/runtests.jl
  test/DGmethods/vars_test.jl
Labels: DG Kernels, MPIStateArray

#821 Import soundings using Artifacts
  test/DGmethods_old/runtests.jl
  test/DGmethods_old/soundings/Artifacts.toml
  test/DGmethods_old/soundings/SOUNDING_PYCLES_Z_T_P.dat
  test/DGmethods_old/soundings/runtests.jl
  test/DGmethods_old/soundings/sounding_DYCOMS_TEST1.dat
  test/DGmethods_old/soundings/sounding_GC1991.dat
  test/DGmethods_old/soundings/sounding_JCP2013.dat
  test/DGmethods_old/soundings/sounding_JCP2013_with_pressure.dat
  test/DGmethods_old/soundings/sounding_WKR88.dat
  test/DGmethods_old/soundings/sounding_blend.dat
Labels: Data

#828 Make Courant absolute time aware
  src/Atmos/Model/courant.jl
  src/DGmethods/DGmodel.jl
  src/DGmethods/DGmodel_kernels.jl
  src/DGmethods/balancelaw.jl
  src/Driver/Driver.jl
  src/Driver/solver_configs.jl
  src/Ocean/HydrostaticBoussinesq/Courant.jl
  test/DGmethods/courant.jl
Labels: Atmos, Defensive programming

#856 Convert Microphysics `saturation_adjustment` driver to new framework
  examples/Microphysics/KinematicModel.jl
  examples/Microphysics/ex_1_saturation_adjustment.jl
  examples/Microphysics/ex_2_Kessler.jl
  slurmci-test.toml
  src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
  src/Atmos/Parameterizations/CloudPhysics/MicrophysicsParameters.jl
  src/Utilities/VariableTemplates/VariableTemplates.jl
  test/Atmos/Parameterizations/Microphysics/runtests.jl
  test/Driver/driver_test.jl
Labels: Microphysics, User Interface

#917 Remove TurbConv framework (which moved to SingleColumnModels.jl)
  docs/make.jl
  docs/src/Atmos/TurbulenceConvection.md
  src/Atmos/Parameterizations/TurbulenceConvection/Grids/FiniteDifferenceGrids.jl
  src/Atmos/Parameterizations/TurbulenceConvection/Grids/GridOperators.jl
  src/Atmos/Parameterizations/TurbulenceConvection/LinearSolvers/TriDiagSolverFuncs.jl
  src/Atmos/Parameterizations/TurbulenceConvection/LinearSolvers/TriDiagSolvers.jl
  src/Atmos/Parameterizations/TurbulenceConvection/README.md
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/BoundaryConditions.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/DomainDecomp.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/DomainDecompFuncs.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/DomainIdx.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/DomainSubSet.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/ExportFuncs.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/ExportFuncsPrimitive.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/PlotFuncs.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/StateVecs.jl
  src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/VarMapper.jl
  src/Atmos/Parameterizations/TurbulenceConvection/TurbulenceConvection.jl
  src/CLIMA.jl
  test/Atmos/Parameterizations/TurbulenceConvection/AdvectionEquation.jl
  test/Atmos/Parameterizations/TurbulenceConvection/DomainDecomp.jl
  test/Atmos/Parameterizations/TurbulenceConvection/FiniteDifferenceGrids.jl
  test/Atmos/Parameterizations/TurbulenceConvection/HeatEquation.jl
  test/Atmos/Parameterizations/TurbulenceConvection/PDEs.jl
  test/Atmos/Parameterizations/TurbulenceConvection/StateVecs.jl
  test/Atmos/Parameterizations/TurbulenceConvection/TDMA.jl
  test/Atmos/Parameterizations/TurbulenceConvection/runtests.jl
  test/Atmos/Parameterizations/runtests.jl
  test/runtests_gpu.jl
Labels: AtmosTCC

#834 Diagnostics update
  Manifest.toml
  Project.toml
  src/Diagnostics/Diagnostics.jl
  src/Diagnostics/atmos_default.jl
  src/Diagnostics/diagnostic_vars.jl
  src/Diagnostics/dump_state_and_aux.jl
  src/Driver/Driver.jl
  src/InputOutput/Writers/Writers.jl
  src/InputOutput/Writers/jld2_writer.jl
  src/InputOutput/Writers/netcdf.jl
  src/InputOutput/Writers/netcdf_writer.jl
  src/Mesh/Interpolation.jl
  test/Diagnostics/sin_test.jl
  test/InputOutput/Writers/runtests.jl
  test/InputOutput/runtests.jl
  test/Mesh/interpolation.jl
  test/runtests.jl
Labels: Diagnostics

#728 User-facing changes to include hyperdiffusion in AtmosModel
  experiments/AtmosLES/risingbubble.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/boundaryconditions.jl
  src/Atmos/Model/hyperdiffusion.jl
  src/Atmos/Model/moisture.jl
  src/Atmos/Model/remainder.jl
  src/DGmethods/NumericalFluxes.jl
Labels: Atmos, Stability, User Interface

#936 Move coverage CI to GitHub Actions
  .github/workflows/Coverage.yaml
  azure-pipelines.yml
Labels: Continuous Integration

#923 Add instructions for precompiling JuliaFormatter
  .dev/hooks/pre-commit.sysimage
  .dev/precompile.jl
  CONTRIBUTING.md
Labels: Documentation

#952 Remove more `PlanetParameters`, add more use of `CLIMAParameters`
  Manifest.toml
  Parameters/EarthParameters.jl
  Parameters/Parameters.jl
  Parameters/Planet.jl
  Project.toml
  docs/src/Atmos/Model/turbulence.md
  examples/Atmos/dry_rayleigh_benard.jl
  examples/Microphysics/KinematicModel.jl
  experiments/AtmosGCM/heldsuarez.jl
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/risingbubble.jl
  experiments/AtmosLES/surfacebubble.jl
  experiments/OceanBoxGCM/homogeneous_box.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/bc_energy.jl
  src/Atmos/Model/boundaryconditions.jl
  src/Atmos/Model/courant.jl
  src/Atmos/Model/hyperdiffusion.jl
  src/Atmos/Model/linear.jl
  src/Atmos/Model/orientation.jl
  src/Atmos/Model/radiation.jl
  src/Atmos/Model/ref_state.jl
  src/Atmos/Model/source.jl
  src/Atmos/Model/turbulence.jl
  src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
  src/CLIMA.jl
  src/Common/MoistThermodynamics/MoistThermodynamics.jl
  src/Common/Parameters/Atmos.jl
  src/Common/Parameters/Parameters.jl
  src/Common/Parameters/Planet.jl
  src/Diagnostics/atmos_default.jl
  src/Driver/Driver.jl
  src/Driver/diagnostics_configs.jl
  src/Driver/driver_configs.jl
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  src/Ocean/ShallowWater/ShallowWaterModel.jl
  test/Common/MoistThermodynamics/runtests.jl
  test/DGmethods/Euler/acousticwave_1d_imex.jl
  test/DGmethods/Euler/isentropicvortex.jl
  test/DGmethods/Euler/isentropicvortex_imex.jl
  test/DGmethods/Euler/isentropicvortex_multirate.jl
  test/DGmethods/compressible_Navier_Stokes/density_current_model.jl
  test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
  test/DGmethods/compressible_Navier_Stokes/ref_state.jl
  test/DGmethods/courant.jl
  test/Diagnostics/diagnostic_fields_test.jl
  test/Diagnostics/sin_test.jl
  test/Driver/cr_unit_tests.jl
  test/Driver/driver_test.jl
  test/Driver/gcm_driver_test.jl
  test/Driver/mms3.jl
  test/Mesh/interpolation.jl
  test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
  test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
  test/Ocean/ShallowWater/GyreDriver.jl
Labels: Free Parameters

#934 Fix CoastlineFreeSlip boundary conditions for HydrostaticBoussinesqModel
  experiments/OceanBoxGCM/homogeneous_box.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  slurmci-test.toml
  src/Driver/solver_configs.jl
  src/Ocean/HydrostaticBoussinesq/BoundaryConditions.jl
  src/Ocean/HydrostaticBoussinesq/Courant.jl
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  src/Ocean/HydrostaticBoussinesq/LinearHBModel.jl
  src/Ocean/HydrostaticBoussinesq/OceanBoundaryConditions.jl
  src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
  test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
  test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
Labels: Boundary Conditions, Ocean, bug

#960 Remove `PlanetParameters` from `SurfaceFluxes`
  src/Atmos/Parameterizations/SurfaceFluxes/SurfaceFluxes.jl
  test/Atmos/Parameterizations/SurfaceFluxes/runtests.jl
Labels: Free Parameters

#861 Support for tracers
  docs/make.jl
  docs/src/Atmos/Model/tracers.md
  docs/src/Atmos/Model/turbulence.md
  examples/Atmos/dry_rayleigh_benard.jl
  experiments/AtmosLES/risingbubble.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/bc_tracer.jl
  src/Atmos/Model/boundaryconditions.jl
  src/Atmos/Model/tracers.jl
Labels: Atmos, enhancement

#924 Add turbulence models to Held-Suarez for 1.5x speedup of simulation
  experiments/AtmosGCM/heldsuarez.jl
  src/Atmos/Model/ref_state.jl
Labels: Atmos

#962 Remove `PlanetParameters`, for good!
  docs/Manifest.toml
  docs/Project.toml
  docs/src/Atmos/Microphysics.md
  examples/Atmos/dry_rayleigh_benard.jl
  examples/DGmethods_old/ex_003_acoustic_wave.jl
  examples/Microphysics/KinematicModel.jl
  examples/Microphysics/ex_1_saturation_adjustment.jl
  examples/Microphysics/ex_2_Kessler.jl
  experiments/AtmosGCM/heldsuarez.jl
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/risingbubble.jl
  experiments/AtmosLES/surfacebubble.jl
  src/Atmos/Model/linear.jl
  src/Atmos/Model/moisture.jl
  src/Atmos/Model/precipitation.jl
  src/Atmos/Model/ref_state.jl
  src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
  src/Atmos/Parameterizations/CloudPhysics/MicrophysicsParameters.jl
  src/Atmos/Parameterizations/SubgridScaleTurbulence/SubgridScaleParameters.jl
  src/Atmos/Parameterizations/SurfaceFluxes/SurfaceFluxes.jl
  src/CLIMA.jl
  src/Common/MoistThermodynamics/MoistThermodynamics.jl
  src/Common/MoistThermodynamics/isentropic.jl
  src/Common/MoistThermodynamics/states.jl
  src/Common/PlanetParameters/EarthConstants.jl
  src/Common/PlanetParameters/PlanetParameters.jl
  src/Common/PlanetParameters/PlanetaryConstants.jl
  src/Common/PlanetParameters/README.md
  src/Common/PlanetParameters/UniversalConstants.jl
  src/Utilities/ParametersType/ParametersType.jl
  src/Utilities/ParametersType/README.md
  test/Atmos/Parameterizations/Microphysics/runtests.jl
  test/Common/MoistThermodynamics/data_tests.jl
  test/Common/MoistThermodynamics/runtests.jl
  test/Common/PlanetParameters/runtests.jl
  test/Common/runtests.jl
  test/DGmethods/Euler/acousticwave_1d_imex.jl
  test/DGmethods/Euler/isentropicvortex.jl
  test/DGmethods/Euler/isentropicvortex_imex.jl
  test/DGmethods/Euler/isentropicvortex_multirate.jl
  test/DGmethods/compressible_Navier_Stokes/density_current_model.jl
  test/DGmethods/courant.jl
  test/DGmethods_old/Euler/RTB_IMEX.jl
  test/Diagnostics/diagnostic_fields_test.jl
  test/Diagnostics/sin_test.jl
  test/Driver/cr_unit_tests.jl
  test/Driver/driver_test.jl
  test/Driver/gcm_driver_test.jl
  test/Mesh/interpolation.jl
  test/Utilities/ParametersType/runtests.jl
  test/Utilities/runtests.jl
  test/runtests_gpu.jl
Labels: Free Parameters

#953 Move documentation to GitHub Actions, enable preview builds
  .github/workflows/Documenter.yaml
  azure-pipelines.yml
  docs/make.jl
Labels: Continuous Integration, Documentation

#975 add DiagnosticVariables.md
  docs/make.jl
  docs/src/DiagnosticVariables.md
  docs/src/VariableList.md
Labels: Documentation

#958 Rework command line arguments
  examples/Atmos/dry_rayleigh_benard.jl
  examples/Microphysics/KinematicModel.jl
  experiments/AtmosGCM/heldsuarez.jl
  experiments/AtmosLES/bomex.jl
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/risingbubble.jl
  experiments/AtmosLES/surfacebubble.jl
  experiments/OceanBoxGCM/ocean_gyre.jl
  src/Arrays/MPIStateArrays.jl
  src/CLIMA.jl
  src/DGmethods/DGmodel.jl
  src/DGmethods/DGmodel_kernels.jl
  src/Diagnostics/Diagnostics.jl
  src/Driver/Driver.jl
  src/Driver/solver_configs.jl
  src/Utilities/Callbacks/Callbacks.jl
  src/Utilities/Checkpoint/Checkpoint.jl
  test/Diagnostics/diagnostic_fields_test.jl
  test/Diagnostics/sin_test.jl
  test/Driver/cr_unit_tests.jl
Labels: User Interface

#986 Apply outline skeleton to docs
  docs/clean_build_folder.jl
  docs/generate.jl
  docs/list_of_apis.jl
  docs/list_of_discussions.jl
  docs/list_of_examples.jl
  docs/list_of_extending_clima.jl
  docs/make.jl
  docs/src/APIs/Arrays/Arrays.md
  docs/src/APIs/Atmos/AtmosModel.md
  docs/src/APIs/Atmos/Microphysics.md
  docs/src/APIs/Common/MoistThermodynamics.md
  docs/src/APIs/Common/SurfaceFluxes.md
  docs/src/APIs/Diagnostics/Diagnostics.md
  docs/src/APIs/Diagnostics/InputOutput.md
  docs/src/APIs/Numerics/DGmethods/BalanceLawOverview.md
  docs/src/APIs/Numerics/DGmethods/DGmethods_old.md
  docs/src/APIs/Numerics/LinearSolvers/LinearSolvers.md
  docs/src/APIs/Numerics/Meshes/Mesh.md
  docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
  docs/src/APIs/index.md
  docs/src/Discussions/Arrays/index.md
  docs/src/Discussions/Atmos/EDMFEquations.md
  docs/src/Discussions/index.md
  docs/src/ExtendingCLIMA/Arrays/index.md
  docs/src/ExtendingCLIMA/Atmos/AtmosModel.md
  docs/src/ExtendingCLIMA/Atmos/Microphysics.md
  docs/src/ExtendingCLIMA/Atmos/Model/tracers.md
  docs/src/ExtendingCLIMA/Atmos/Model/turbulence.md
  docs/src/ExtendingCLIMA/Common/MoistThermodynamics.md
  docs/src/ExtendingCLIMA/Common/SurfaceFluxes.md
  docs/src/ExtendingCLIMA/Contributing/CONTRIBUTING.md
  docs/src/ExtendingCLIMA/Diagnostics/DiagnosticVariables.md
  docs/src/ExtendingCLIMA/Land/index.md
  docs/src/ExtendingCLIMA/Numerics/DGmethods/how_to_make_a_balance_law.md
  docs/src/ExtendingCLIMA/Numerics/LinearSolvers/IterativeSolvers.md
  docs/src/ExtendingCLIMA/Numerics/Meshes/index.md
  docs/src/ExtendingCLIMA/Numerics/ODESolvers/index.md
  docs/src/ExtendingCLIMA/Ocean/index.md
  docs/src/Installation.md
  examples/Numerics/LinearSolvers/cg.jl
  examples/literate_markdown.jl
Labels: Documentation

#970 Installation instructions in documentation
  README.md
  docs/src/Installation.md
Labels: Documentation

#988 Move ex_004_nonnegative.jl to the new framework
  examples/DGmethods_old/ex_004_nonnegative.jl
  examples/Numerics/DGmethods/nonnegative.jl
  slurmci-test.toml
  test/Numerics/DGmethods/advection_diffusion/advection_diffusion_model.jl
Labels: Documentation

#997 Update moist thermo doc strings
  src/Common/MoistThermodynamics/MoistThermodynamics.jl
  src/Common/MoistThermodynamics/isentropic.jl
  src/Common/MoistThermodynamics/states.jl
Labels: Documentation, moist-thermo

#1001 Rename `examples` to `tutorials`
  .gitignore
  docs/list_of_examples.jl
  docs/list_of_tutorials.jl
  docs/make.jl
  docs/src/Installation.md
  slurmci-test.toml
  tutorials/Atmos/dry_rayleigh_benard.jl
  tutorials/Microphysics/KinematicModel.jl
  tutorials/Microphysics/ex_1_saturation_adjustment.jl
  tutorials/Microphysics/ex_2_Kessler.jl
  tutorials/Numerics/DGmethods/nonnegative.jl
  tutorials/Numerics/DGmethods_old/ex_001_periodic_advection.jl
  tutorials/Numerics/DGmethods_old/ex_002_solid_body_rotation.jl
  tutorials/Numerics/DGmethods_old/ex_003_acoustic_wave.jl
  tutorials/Numerics/LinearSolvers/cg.jl
  tutorials/literate_markdown.jl
  tutorials/topo.jl
Labels: Documentation

#1000 Timestepping contribution guide
  docs/list_of_extending_clima.jl
  docs/src/ExtendingCLIMA/Numerics/ODESolvers/Timestepping.md
  docs/src/ExtendingCLIMA/Numerics/ODESolvers/index.md
Labels: Documentation, Timestepping

#1016 Bugfix -(issue #1009)
  experiments/AtmosLES/dycoms.jl
  src/Numerics/DGmethods/DGmodel_kernels.jl
Labels: Atmos, Bug-fix

#974 More LES diagnostics
  docs/src/ExtendingCLIMA/Diagnostics/DiagnosticVariables.md
  src/Diagnostics/Diagnostics.jl
  src/Diagnostics/atmos_core.jl
  src/Diagnostics/atmos_default.jl
  src/Diagnostics/dump_state_and_aux.jl
  src/Diagnostics/thermo.jl
  src/InputOutput/Writers/Writers.jl
  src/InputOutput/Writers/jld2_writer.jl
  src/InputOutput/Writers/netcdf_writer.jl
  test/Diagnostics/sin_test.jl
  test/InputOutput/Writers/runtests.jl
Labels: Diagnostics

#994 Adding Held-Suarez example documentation
  docs/list_of_tutorials.jl
  tutorials/Atmos/heldsuarez.jl
Labels: Documentation

#1020 Turn off Azure CI on master
  azure-pipelines.yml
Labels: Continuous Integration

#992 AtmosModel example 1
  docs/list_of_tutorials.jl
  docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
  docs/src/ExtendingCLIMA/Atmos/AtmosModel.md
  docs/src/ExtendingCLIMA/Atmos/Model/risingbubble.md
  docs/src/ExtendingCLIMA/Atmos/Model/tracers.md
  docs/src/ExtendingCLIMA/Atmos/Model/turbulence.md
  docs/src/ExtendingCLIMA/Common/MoistThermodynamics.md
  experiments/AtmosLES/risingbubble.jl
Labels: Documentation

#1019 Add atmosphere 'core' diagnostics
  experiments/AtmosLES/bomex.jl
  src/Diagnostics/Diagnostics.jl
  src/Diagnostics/atmos_common.jl
  src/Diagnostics/atmos_core.jl
  src/Diagnostics/atmos_default.jl
  src/Diagnostics/thermo.jl
  src/InputOutput/VTK/writevtk.jl
Labels: Diagnostics

#1033 Add docs file filter
  docs/list_of_tutorials.jl
Labels: Documentation
