Repository CliMA/ClimateMachine.jl, pull requests merged in 2020-12, with the labels that each got.

#1803 Add missing call to rain source
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/moisture.jl
  src/Atmos/Model/precipitation.jl
Labels: Bug-fix

#1799 Move radiation to new tendency spec
  experiments/AtmosLES/dycoms.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/radiation.jl
Labels: Refactor

#1794 Revamp bomex EDMF regression test
  docs/plothelpers.jl
  src/BalanceLaws/show_tendencies.jl
  test/Atmos/EDMF/Artifacts.toml
  test/Atmos/EDMF/bomex_edmf.jl
  test/Atmos/EDMF/bomex_edmf_regression_test.jl
  test/Atmos/EDMF/compute_mse.jl
  test/Atmos/EDMF/report_mse.jl
  test/Atmos/EDMF/variable_map.jl
Labels: AtmosTCC

#1813 add simple rain CI checks
  .buildkite/pipeline.yml
  experiments/AtmosLES/dycoms.jl
Labels: Atmos, CI, tests

#1800 Move first order rain flux to new tend spec
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/precipitation.jl
Labels: Refactor

#1819 Move tracers first order flux to new tendency specification
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/declare_prognostic_vars.jl
  src/Atmos/Model/get_prognostic_vars.jl
  src/Atmos/Model/tracers.jl
  src/BalanceLaws/show_tendencies.jl
Labels: Refactor

#1702 Kernel infrastructure for supporting variable-degree data structures
  .buildkite/pipeline.yml
  .github/workflows/CompatHelper.yml
  .github/workflows/Coverage.yaml
  .github/workflows/Documenter.yaml
  .github/workflows/JuliaFormatter.yml
  .github/workflows/Linux-UnitTests.yml
  .github/workflows/OS-UnitTests.yml
  src/Driver/driver_configs.jl
  src/Numerics/DGMethods/DGModel.jl
  src/Numerics/DGMethods/DGModel_kernels.jl
  src/Numerics/DGMethods/NumericalFluxes.jl
  src/Numerics/DGMethods/custom_filter.jl
  src/Numerics/Mesh/Geometry.jl
  src/Numerics/Mesh/Grids.jl
  src/Numerics/SystemSolvers/batched_generalized_minimal_residual_solver.jl
  src/Numerics/SystemSolvers/columnwise_lu_solver.jl
  src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
  src/Ocean/SplitExplicit/Communication.jl
  src/Ocean/SplitExplicit/HydrostaticBoussinesqCoupling.jl
  src/Ocean/SplitExplicit01/Communication.jl
  src/Ocean/SplitExplicit01/OceanModel.jl
  src/Utilities/SingleStackUtils/SingleStackUtils.jl
  test/Driver/driver_test.jl
  test/Driver/gcm_driver_test.jl
  test/Numerics/DGMethods/Euler/acousticwave_variable_degree.jl
  test/Numerics/DGMethods/advection_diffusion/diffusion_hyperdiffusion_sphere.jl
  test/Numerics/DGMethods/advection_diffusion/direction_splitting_advection_diffusion.jl
  test/Numerics/DGMethods/advection_diffusion/variable_degree_advection_diffusion.jl
  test/Numerics/Mesh/min_node_distance.jl
  test/Numerics/SystemSolvers/columnwiselu.jl
  test/Ocean/HydrostaticBoussinesq/test_3D_spindown.jl
  test/Ocean/SplitExplicit/hydrostatic_spindown.jl
  test/Utilities/SingleStackUtils/ssu_tests.jl
Labels: DG Kernels, Numerics 🔢, interface change

#1821 Change `all_data` to `dons_arr`
  docs/src/HowToGuides/Atmos/AtmosReferenceState.md
  test/Atmos/EDMF/stable_bl_edmf.jl
  test/Atmos/EDMF/stable_bl_edmf_implicit.jl
  test/Atmos/Model/ref_state.jl
  test/Land/Model/freeze_thaw_alone.jl
  test/Land/Model/test_bc.jl
  tutorials/Land/Heat/heat_equation.jl
  tutorials/Land/Soil/Coupled/equilibrium_test.jl
  tutorials/Land/Soil/Water/equilibrium_test.jl
  tutorials/Numerics/DGMethods/Box1D.jl
Labels: Naming Conventions

#1825 Move first order flux turbconv tendencies to new spec
  src/Atmos/Model/get_prognostic_vars.jl
  src/Common/TurbulenceConvection/TurbulenceConvection.jl
  test/Atmos/EDMF/edmf_kernels.jl
Labels: Refactor

#1822 Move bomex and convective/dry BL sources to new tend spec
  experiments/AtmosLES/bomex_model.jl
  experiments/AtmosLES/convective_bl_model.jl
  experiments/AtmosLES/stable_bl_model.jl
Labels: Refactor

#1828 Improve balance law comments / docs, update some names
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/tendencies_energy.jl
  src/BalanceLaws/tendency_types.jl
Labels: Documentation 📜, Naming Conventions

#1820 Adaptive timestepping callback
  docs/src/APIs/Driver/index.md
  docs/src/GettingStarted/RunningClimateMachine.md
  src/Driver/Callbacks/Callbacks.jl
  src/Driver/Driver.jl
  src/Driver/SolverTypes/SolverTypes.jl
  src/Driver/solver_configs.jl
Labels: Timestepping

#1763 Add density-pressure thermo constructors
  docs/src/APIs/Common/Thermodynamics.md
  src/Common/Thermodynamics/relations.jl
  src/Common/Thermodynamics/states.jl
  test/Common/Thermodynamics/runtests.jl
Labels: Thermodynamics

#1801 Move held suarez sources to new tend spec
  experiments/AtmosGCM/GCMDriver/GCMDriver.jl
  experiments/AtmosGCM/GCMDriver/gcm_sources.jl
  experiments/AtmosGCM/GCMDriver/heldsuarez_problem.jl
  experiments/AtmosGCM/heldsuarez.jl
  src/Atmos/Model/tendencies_momentum.jl
  tutorials/Atmos/heldsuarez.jl
Labels: Refactor

#1824 Let it snow
  .buildkite/pipeline.yml
  docs/src/APIs/Atmos/AtmosModel.md
  docs/src/HowToGuides/Atmos/PrecipitationModelChoices.md
  docs/src/Theory/Atmos/Microphysics.md
  docs/src/Theory/Atmos/Microphysics_0M.md
  experiments/AtmosLES/dycoms.jl
  experiments/AtmosLES/squall_line.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/bc_precipitation.jl
  src/Atmos/Model/boundaryconditions.jl
  src/Atmos/Model/get_prognostic_vars.jl
  src/Atmos/Model/multiphysics_types.jl
  src/Atmos/Model/precipitation.jl
  src/Atmos/Model/source.jl
  src/Atmos/Model/tendencies_energy.jl
  src/Atmos/Model/tendencies_mass.jl
  src/Atmos/Model/tendencies_moisture.jl
  src/Atmos/Model/tendencies_precipitation.jl
  src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
  src/Diagnostics/atmos_les_default.jl
  src/Diagnostics/variables.jl
Labels: Atmos, Microphysics

#1840 Move second order rain flux to new tend spec
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/multiphysics_types.jl
  src/Atmos/Model/precipitation.jl
  src/Atmos/Model/tendencies_precipitation.jl
Labels: Refactor

#1848 cleanup in multiphysics sources
  src/Atmos/Model/multiphysics_types.jl
  src/Atmos/Model/tendencies_energy.jl
  src/Atmos/Model/tendencies_mass.jl
  src/Atmos/Model/tendencies_moisture.jl
  src/Atmos/Model/tendencies_precipitation.jl
Labels: Atmos, Microphysics

#1835 Update diagnostics groups to handle variable degrees
  .buildkite/pipeline.yml
  experiments/AtmosLES/bomex_les.jl
  experiments/AtmosLES/dycoms.jl
  src/Diagnostics/atmos_common.jl
  src/Diagnostics/atmos_gcm_default.jl
  src/Diagnostics/atmos_les_core.jl
  src/Diagnostics/atmos_les_default.jl
  src/Diagnostics/atmos_les_default_perturbations.jl
  src/Diagnostics/atmos_refstate_perturbations.jl
  src/Diagnostics/helpers.jl
  src/Diagnostics/thermo.jl
Labels: Diagnostics

#1852 Add thermo ProfileSet Iterator
  test/Common/Thermodynamics/profiles.jl
  test/Common/Thermodynamics/runtests.jl
Labels: Thermodynamics

#1853 add moisture and precipitation asserts to squall line CI
  .buildkite/pipeline.yml
  experiments/AtmosLES/squall_line.jl
Labels: Atmos, CI, Microphysics, tests

#1860 Fix race condition in Squal line artifact
  experiments/AtmosLES/squall_line.jl
Labels: Bug-fix

#1846 Vorticity from Atmos DGModel output by Diagnostics
  .buildkite/pipeline.yml
  docs/src/DevDocs/DiagnosticVariableList.md
  src/Diagnostics/atmos_gcm_default.jl
  src/Diagnostics/variables.jl
  src/Diagnostics/vorticity_balancelaw.jl
Labels: Diagnostics

#1834 Move second order moisture flux to new tend spec
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/moisture.jl
  src/Atmos/Model/multiphysics_types.jl
  src/Atmos/Model/tendencies_mass.jl
  src/Atmos/Model/tendencies_moisture.jl
  src/Atmos/Model/tendencies_momentum.jl
Labels: Refactor

#1864 Move precompute method to balance law
  docs/src/APIs/BalanceLaws/BalanceLaws.md
  src/Atmos/Model/AtmosModel.jl
  src/BalanceLaws/BalanceLaws.jl
  src/BalanceLaws/tendency_types.jl
Labels: Refactor

#1868 fixes to squall line experiment for QA-Microphysics
  experiments/AtmosLES/squall_line.jl
Labels: Atmos, Microphysics

#1849 Fix second order rain flux
  src/Atmos/Model/multiphysics_types.jl
  src/Atmos/Model/precipitation.jl
  src/Atmos/Model/tendencies_precipitation.jl
Labels: Bug-fix

#1871 Import prim-prog in AtmosModel
  src/Atmos/Model/AtmosModel.jl
  test/Atmos/prog_prim_conversion/runtests.jl
Labels: Bug-fix

#1865 Reformulate first order flux arguments, add precomputed NamedTuple
  experiments/AtmosLES/dycoms.jl
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/moisture.jl
  src/Atmos/Model/precipitation.jl
  src/Atmos/Model/tendencies_energy.jl
  src/Atmos/Model/tendencies_mass.jl
  src/Atmos/Model/tendencies_moisture.jl
  src/Atmos/Model/tendencies_momentum.jl
  src/Atmos/Model/tendencies_precipitation.jl
  src/Atmos/Model/tendencies_tracers.jl
  src/Atmos/Model/tracers.jl
  src/Common/TurbulenceConvection/TurbulenceConvection.jl
  test/Atmos/EDMF/edmf_kernels.jl
Labels: Refactor

#1869 Make swapping sat adjust numerical methods easier, add GPU tests
  .buildkite/pipeline.yml
  Manifest.toml
  Project.toml
  src/Common/Thermodynamics/Thermodynamics.jl
  src/Common/Thermodynamics/config_numerical_method.jl
  src/Common/Thermodynamics/relations.jl
  src/Common/Thermodynamics/states.jl
  test/Common/Thermodynamics/profiles.jl
  test/Common/Thermodynamics/runtests.jl
  test/Common/Thermodynamics/runtests_gpu.jl
Labels: Refactor, Thermodynamics

#1866 Add moisture and precipitation tutorial
  docs/list_of_how_to_guides.jl
  docs/src/HowToGuides/Atmos/MoistureAndPrecip.md
Labels: Atmos, Documentation 📜, Microphysics

#1876 Add TKE budget variables to GradientFlux().
  test/Atmos/EDMF/edmf_kernels.jl
  test/Atmos/EDMF/stable_bl_edmf.jl
Labels: EDMF

#1886 EKE power spectrum diagnostic for the baroclinic_wave test
  experiments/TestCase/baroclinic_wave.jl
Labels: Diagnostics

#1877 Move hyperdiffusion fluxes to new tend spec
  docs/src/APIs/Common/TurbulenceClosures.md
  src/Atmos/Model/AtmosModel.jl
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/tendencies_energy.jl
  src/Atmos/Model/tendencies_moisture.jl
  src/Atmos/Model/tendencies_momentum.jl
  src/Common/TurbulenceClosures/TurbulenceClosures.jl
Labels: Refactor

#1891 Detect CI environments and download Artifacts to unique path prefixes
  experiments/AtmosLES/cfsite_hadgem2-a_07_amip.jl
  experiments/AtmosLES/squall_line.jl
  test/Atmos/EDMF/compute_mse.jl
  test/Atmos/Model/ref_state.jl
  test/Common/Thermodynamics/data_tests.jl
  test/Land/Model/haverkamp_implicit_test.jl
  test/Land/Model/haverkamp_test.jl
  tutorials/Land/Soil/Heat/bonan_heat_tutorial.jl
Labels: CI

#1889 Fix L_w, move turb closure to experiment, prepare for grid-mean coupling.
  experiments/AtmosLES/stable_bl_les.jl
  experiments/AtmosLES/stable_bl_model.jl
  test/Atmos/EDMF/closures/mixing_length.jl
  test/Atmos/EDMF/edmf_kernels.jl
  test/Atmos/EDMF/edmf_model.jl
  test/Atmos/EDMF/report_mse.jl
  test/Atmos/EDMF/stable_bl_single_stack_implicit.jl
Labels: EDMF

#1892 Cache some computations in turbconv
  docs/src/Theory/Atmos/EDMF_plots.md
  src/Atmos/Model/AtmosModel.jl
  src/Common/TurbulenceConvection/TurbulenceConvection.jl
  test/Atmos/EDMF/bomex_edmf.jl
  test/Atmos/EDMF/closures/entr_detr.jl
  test/Atmos/EDMF/closures/mixing_length.jl
  test/Atmos/EDMF/closures/pressure.jl
  test/Atmos/EDMF/closures/turbulence_functions.jl
  test/Atmos/EDMF/edmf_kernels.jl
  test/Atmos/EDMF/helper_funcs/nondimensional_exchange_functions.jl
  test/Atmos/EDMF/helper_funcs/subdomain_statistics.jl
  test/Atmos/EDMF/report_mse_bomex.jl
Labels: Refactor

#1895 Add kwarg flexibility to plothelpers.jl
  docs/plothelpers.jl
Labels: plotting
