Repository CliMA/ClimateMachine.jl, pull requests merged in 2021-01, with the labels that each got.

#1899 Add turbconv fluxes and sources tendency specification layer
  src/Atmos/Model/atmos_tendencies.jl
  src/Atmos/Model/multiphysics_types.jl
  src/Common/TurbulenceConvection/TurbulenceConvection.jl
  test/Atmos/EDMF/bomex_edmf.jl
  test/Atmos/EDMF/edmf_kernels.jl
  test/Atmos/EDMF/report_mse_bomex.jl
Labels: Refactor

#1898 Fix temp BCs for SBL.
  experiments/AtmosLES/stable_bl_model.jl
Labels: EDMF

#1901 Fix +- bug in single stack utils
  src/Utilities/SingleStackUtils/SingleStackUtils.jl
Labels: Bug-fix

#1906 Add NodalStack utils and iterator
  docs/src/APIs/Utilities/SingleStackUtils.md
  src/Utilities/SingleStackUtils/SingleStackUtils.jl
  test/Utilities/SingleStackUtils/ssu_tests.jl
Labels: Diagnostics

#1903 Allow updraft zero area fraction
  src/Atmos/Model/AtmosModel.jl
  test/Atmos/EDMF/closures/entr_detr.jl
  test/Atmos/EDMF/closures/mixing_length.jl
  test/Atmos/EDMF/closures/pressure.jl
  test/Atmos/EDMF/edmf_kernels.jl
  test/Atmos/EDMF/helper_funcs/nondimensional_exchange_functions.jl
  test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
  test/Atmos/EDMF/helper_funcs/utility_funcs.jl
  test/Atmos/EDMF/report_mse_bomex.jl
Labels: EDMF

#1917 Add single stack diagnostics, replace dons in some experiments
  docs/src/APIs/Utilities/SingleStackUtils.md
  docs/src/APIs/Utilities/VariableTemplates.md
  src/Driver/driver_configs.jl
  src/Driver/solver_config_wrappers.jl
  src/Driver/solver_configs.jl
  src/Utilities/SingleStackUtils/SingleStackUtils.jl
  src/Utilities/SingleStackUtils/single_stack_diagnostics.jl
  src/Utilities/VariableTemplates/VariableTemplates.jl
  src/Utilities/VariableTemplates/flattened_tup_chain.jl
  test/Atmos/EDMF/bomex_edmf.jl
  test/Atmos/EDMF/report_mse_bomex.jl
  test/Atmos/EDMF/stable_bl_edmf.jl
  test/Atmos/EDMF/stable_bl_single_stack_implicit.jl
  test/Utilities/VariableTemplates/test_complex_models.jl
Labels: Diagnostics

#1861 small update of an offline test
  src/Common/Spectra/power_spectrum_gcm.jl
  src/Diagnostics/atmos_gcm_spectra.jl
  test/Common/Spectra/gcm_standalone_visual_test.jl
  test/Common/Spectra/runtests.jl
Labels: Diagnostics

#1928 Add thermo mixing ratio functions
  docs/src/APIs/Common/Thermodynamics.md
  src/Common/Thermodynamics/relations.jl
  test/Common/Thermodynamics/runtests.jl
Labels: Thermodynamics

#1946 Add element and domain sizes CL options
  src/Driver/Driver.jl
  src/Driver/driver_configs.jl
  test/Driver/les_driver_test.jl
  test/Driver/runtests.jl
Labels: User Interface, enhancement

#1931 Fix NamedTuple keys, add error handling
  src/Utilities/SingleStackUtils/single_stack_diagnostics.jl
  src/Utilities/VariableTemplates/VariableTemplates.jl
  src/Utilities/VariableTemplates/flattened_tup_chain.jl
  test/Utilities/VariableTemplates/test_complex_models.jl
Labels: Bug-fix

#1961 Add tests for ArtifactWrappers
  test/InputOutput/ArtifactWrappers/runtests.jl
  test/InputOutput/runtests.jl
Labels: tests

#1944 Adjust diagnostics output for BOMEX single stack and BOMEX EDMF
  .buildkite/pipeline.yml
  experiments/AtmosLES/bomex_les.jl
  experiments/AtmosLES/bomex_model.jl
  experiments/AtmosLES/bomex_single_stack.jl
  src/Driver/driver_configs.jl
  test/Atmos/EDMF/bomex_edmf.jl
Labels: Diagnostics

#1971 Move long tests to buildkite
  .buildkite/pipeline.yml
  test/Numerics/DGMethods/runtests.jl
  test/Numerics/Mesh/runtests.jl
  test/Numerics/ODESolvers/runtests.jl
  test/Numerics/SystemSolvers/runtests.jl
  test/Numerics/runtests.jl
Labels: CI
